### ISSUE TITLE
Bad credentials error when trying to post comment to GitHub

### ISSUE THREAD

**Issue by HCastano** [paritytech/ink-waterfall#20]
If you take a look at the [CI output](https://gitlab.parity.io/parity/ink-waterfall/-/jobs/1353044) of [this test PR](https://github.com/paritytech/ink/pull/1113) you can see that while the `ink-waterfall` pipeline succeeded no comment actually got posted on GitHub due to a "Bad credentials" error.

There's probably an outdated access token somewhere that we need to update.

**Comment by cmichi** [comment]
I think this `GITHUB_TOKEN` here stopped working: https://github.com/paritytech/ink-waterfall/blob/master/.gitlab-ci.yml#L35-L37.

@alvicsam You recently updated another token, could it be that this token needs to be updated as well?

**Comment by alvicsam** [comment]
I applied a temporary fix so it works now. But I need to make a few adjustments in the future
